repo:
  clone_url: "https://github.com/nsavinda/go-test-server.git"
  branch: "main"

service:
  name: myservice
  clonePath: /home/nirmal/Project/elixir-craft/AutoPuller/deployments/
  execFile: main
  preStartHook:  /home/nirmal/Project/elixir-craft/AutoPuller/deployments/%i/build.sh
  listenPort: 8700
  destPorts:
    - 8701
    - 8702
  